use assert_cmd::Command;
use predicates::prelude::*;
use tempfile::TempDir;

struct TestSetup {
    config_dir: TempDir,
    home_dir: TempDir,
    work_dir: TempDir,
}

impl TestSetup {
    fn new() -> Self {
        TestSetup {
            config_dir: TempDir::new().unwrap(),
            home_dir: TempDir::new().unwrap(),
            work_dir: TempDir::new().unwrap(),
        }
    }

    fn write_project(&self, name: &str, content: &str) {
        std::fs::write(self.config_dir.path().join(format!("{name}.yml")), content).unwrap();
    }

    fn cmd(&self) -> Command {
        let mut cmd = Command::cargo_bin("bootmux").unwrap();
        cmd.env_clear()
            .env("PATH", std::env::var("PATH").unwrap())
            .env("HOME", self.home_dir.path())
            .env("TMUXINATOR_CONFIG", self.config_dir.path())
            .env("SHELL", "/bin/bash")
            .env("EDITOR", "true")
            .current_dir(self.work_dir.path());
        cmd
    }

    #[cfg(unix)]
    fn install_fake_fzf(&self, script: &str) -> std::path::PathBuf {
        use std::os::unix::fs::PermissionsExt;

        let bin = self.work_dir.path().join("bin");
        std::fs::create_dir_all(&bin).unwrap();
        let fzf = bin.join("fzf");
        std::fs::write(&fzf, script).unwrap();
        std::fs::set_permissions(&fzf, std::fs::Permissions::from_mode(0o700)).unwrap();
        fzf
    }

    #[cfg(unix)]
    fn cmd_with_fake_fzf(&self, script: &str) -> Command {
        let fzf = self.install_fake_fzf(script);
        let mut cmd = self.cmd();
        let parent = fzf.parent().unwrap();
        cmd.env(
            "PATH",
            format!("{}:{}", parent.display(), std::env::var("PATH").unwrap()),
        );
        cmd
    }

    #[cfg(unix)]
    fn cmd_with_supported_tmux(&self) -> Command {
        self.cmd_with_fake_multiplexer(
            "tmux",
            "#!/bin/sh\nif [ \"${1:-}\" = \"-V\" ]; then\n  printf 'tmux 3.4\\n'\nfi\n",
        )
    }

    #[cfg(unix)]
    fn cmd_with_supported_zellij(&self) -> Command {
        self.cmd_with_fake_multiplexer(
            "zellij",
            "#!/bin/sh\nif [ \"${1:-}\" = \"--version\" ]; then\n  \
             printf 'zellij 0.44.3\\n'\nfi\n",
        )
    }

    #[cfg(unix)]
    fn cmd_with_fake_multiplexer(&self, name: &str, script: &str) -> Command {
        use std::os::unix::fs::PermissionsExt;

        let bin = self.work_dir.path().join("bin");
        std::fs::create_dir_all(&bin).unwrap();
        let binary = bin.join(name);
        std::fs::write(&binary, script).unwrap();
        std::fs::set_permissions(&binary, std::fs::Permissions::from_mode(0o700)).unwrap();

        let mut cmd = self.cmd();
        cmd.env(
            "PATH",
            format!("{}:{}", bin.display(), std::env::var("PATH").unwrap()),
        );
        cmd
    }
}

const VALID_PROJECT: &str = "name: valid\nattach: false\nwindows:\n  - editor: vim\n";

#[test]
fn version_prints_bootmux_version() {
    let setup = TestSetup::new();
    setup
        .cmd()
        .arg("version")
        .assert()
        .success()
        .stdout(format!("bootmux {}\n", env!("CARGO_PKG_VERSION")));

    setup
        .cmd()
        .arg("-v")
        .assert()
        .success()
        .stdout(predicate::str::starts_with("bootmux "));

    for flag in ["-V", "--version"] {
        setup
            .cmd()
            .arg(flag)
            .assert()
            .success()
            .stdout(format!("bootmux {}\n", env!("CARGO_PKG_VERSION")));
    }
}

#[test]
fn help_documents_bare_invocation_and_missing_backend_stays_a_parse_error() {
    let setup = TestSetup::new();
    setup
        .cmd()
        .arg("--help")
        .assert()
        .success()
        .stdout(predicate::str::contains(
            "Usage: bootmux [OPTIONS] [COMMAND]",
        ));

    setup
        .cmd()
        .arg("--backend")
        .assert()
        .failure()
        .stderr(predicate::str::contains("a value is required"))
        .stderr(predicate::str::contains("picker").not());
}

#[test]
fn commands_lists_all_command_names() {
    let setup = TestSetup::new();
    let assert = setup.cmd().arg("commands").assert().success();
    let output = String::from_utf8(assert.get_output().stdout.clone()).unwrap();
    for name in ["start", "stop", "stop_all", "debug", "implode", "version"] {
        assert!(output.lines().any(|line| line == name), "missing {name}");
    }

    setup
        .cmd()
        .args(["commands", "zsh"])
        .assert()
        .success()
        .stdout(predicate::str::contains(
            "debug:Output the shell commands that are generated by bootmux",
        ));
}

#[test]
fn completions_lists_projects_for_completable_commands() {
    let setup = TestSetup::new();
    setup.write_project("alpha", VALID_PROJECT);
    setup.write_project("beta", VALID_PROJECT);

    setup
        .cmd()
        .args(["completions", "start"])
        .assert()
        .success()
        .stdout("alpha\nbeta\n");

    setup
        .cmd()
        .args(["completions", "doctor"])
        .assert()
        .success()
        .stdout("");
}

#[test]
fn list_shows_projects() {
    let setup = TestSetup::new();
    setup.write_project("alpha", VALID_PROJECT);
    setup.write_project("beta", VALID_PROJECT);

    setup
        .cmd()
        .args(["list", "--newline"])
        .assert()
        .success()
        .stdout("bootmux projects:\nalpha\nbeta\n");
}

#[test]
fn debug_renders_project_script() {
    let setup = TestSetup::new();
    setup.write_project("demo", "name: demo\nwindows:\n  - editor: vim\n");

    setup
        .cmd()
        .args(["debug", "demo"])
        .assert()
        .success()
        .stdout(predicate::str::contains("new-session -d -s demo -n editor"))
        .stdout(predicate::str::contains("vim C-m"));
}

#[test]
fn debug_accepts_project_config_path_and_settings() {
    let setup = TestSetup::new();
    let config = setup.work_dir.path().join("templated.yml");
    std::fs::write(
        &config,
        "name: {{ settings.session | default('fallback') }}\nwindows:\n  - a: echo {{ args[0] }}\n",
    )
    .unwrap();

    setup
        .cmd()
        .args([
            "debug",
            "-p",
            config.to_str().unwrap(),
            "session=custom",
            "hello",
        ])
        .assert()
        .success()
        .stdout(predicate::str::contains("new-session -d -s custom"))
        .stdout(predicate::str::contains("echo\\ hello C-m"));
}

#[test]
fn stop_accepts_the_same_template_settings_and_args_as_start() {
    let setup = TestSetup::new();
    let project = setup.work_dir.path().join("dynamic-stop.yml");
    let config = r#"name: <%= @settings["name"] %>
tmux_command: true
socket_name: <%= @settings["name"] %>
on_project_stop: test '{{ args[0] }}' = sentinel
windows:
  - editor: echo ready
"#;
    std::fs::write(&project, config).unwrap();
    setup.write_project("dynamic", config);

    setup
        .cmd()
        .args([
            "--backend",
            "tmux",
            "stop",
            "--project-config",
            project.to_str().unwrap(),
            "name=dynamic",
            "sentinel",
            "--suppress-tmux-version-warning",
        ])
        .assert()
        .success();

    setup
        .cmd()
        .args([
            "--backend",
            "tmux",
            "stop",
            "dynamic",
            "name=dynamic",
            "sentinel",
            "--suppress-tmux-version-warning",
        ])
        .assert()
        .success();
}

#[test]
#[cfg(unix)]
fn project_name_shorthand_routes_to_start() {
    let setup = TestSetup::new();
    setup.write_project("broken", "name: broken\nwindows: []\n");

    setup
        .cmd_with_supported_tmux()
        .arg("broken")
        .assert()
        .code(1)
        .stdout("Your project file should include some windows.\n");
}

#[test]
#[cfg(unix)]
fn bare_invocation_uses_local_project_file() {
    let setup = TestSetup::new();
    std::fs::write(
        setup.work_dir.path().join(".tmuxinator.yml"),
        "name: local-broken\nwindows: []\n",
    )
    .unwrap();

    setup
        .cmd_with_supported_tmux()
        .assert()
        .code(1)
        .stdout("Your project file should include some windows.\n");
}

#[test]
#[cfg(unix)]
fn missing_projects_report_ruby_compatible_errors() {
    let setup = TestSetup::new();

    setup
        .cmd_with_supported_tmux()
        .args(["start", "nosuch"])
        .assert()
        .code(1)
        .stdout("Project nosuch doesn't exist.\n");

    setup
        .cmd_with_supported_tmux()
        .args(["stop"])
        .assert()
        .code(1)
        .stdout("Project file at ./.tmuxinator.yml doesn't exist.\n");

    setup
        .cmd_with_supported_tmux()
        .args(["debug", "-p", "missing.yml"])
        .assert()
        .code(1)
        .stdout("Project config (missing.yml) doesn't exist.\n");
}

#[test]
fn erb_configs_are_rejected_with_migration_hint() {
    let setup = TestSetup::new();
    setup.write_project(
        "legacy",
        "name: legacy\nwindows:\n  - a: echo <%= @args[0] %>\n",
    );

    setup
        .cmd()
        .args(["debug", "legacy"])
        .assert()
        .code(1)
        .stdout(predicate::str::contains("Failed to parse config file:"))
        .stdout(predicate::str::contains("MiniJinja"));
}

#[test]
fn new_generates_project_from_sample_and_opens_editor() {
    let setup = TestSetup::new();

    setup.cmd().args(["new", "fresh"]).assert().success();

    let created = setup.config_dir.path().join("fresh.yml");
    let content = std::fs::read_to_string(&created).unwrap();
    assert!(content.contains("name: fresh"));
    assert!(content.contains(created.to_str().unwrap()));
}

#[test]
fn copy_duplicates_project_files() {
    let setup = TestSetup::new();
    setup.write_project("origin", VALID_PROJECT);

    setup
        .cmd()
        .args(["copy", "origin", "clone"])
        .assert()
        .success();
    assert!(setup.config_dir.path().join("clone.yml").exists());

    setup
        .cmd()
        .args(["copy", "nosuch", "clone2"])
        .assert()
        .code(1)
        .stdout("Project nosuch doesn't exist!\n");
}

#[test]
fn delete_removes_project_after_confirmation() {
    let setup = TestSetup::new();
    setup.write_project("doomed", VALID_PROJECT);

    setup
        .cmd()
        .args(["delete", "doomed"])
        .write_stdin("y\n")
        .assert()
        .success()
        .stdout(predicate::str::contains("Deleted doomed"));
    assert!(!setup.config_dir.path().join("doomed.yml").exists());

    setup
        .cmd()
        .args(["delete", "ghost"])
        .assert()
        .success()
        .stdout(predicate::str::contains("ghost does not exist!"));
}

#[test]
fn deleting_a_missing_named_project_never_deletes_the_local_project() {
    let setup = TestSetup::new();
    let local = setup.work_dir.path().join(".tmuxinator.yml");
    std::fs::write(&local, VALID_PROJECT).unwrap();

    setup
        .cmd()
        .args(["delete", "ghost"])
        .write_stdin("y\n")
        .assert()
        .success()
        .stdout("ghost does not exist!\n");

    assert_eq!(std::fs::read_to_string(local).unwrap(), VALID_PROJECT);
}

#[test]
fn command_aliases_win_over_conflicting_global_project_names() {
    let setup = TestSetup::new();
    setup.write_project("l", VALID_PROJECT);
    setup.write_project("st", VALID_PROJECT);

    setup
        .cmd()
        .args(["l", "--help"])
        .assert()
        .success()
        .stdout(predicate::str::starts_with("Lists all bootmux projects"));
    setup
        .cmd()
        .args(["st", "--help"])
        .assert()
        .success()
        .stdout(predicate::str::starts_with(
            "Stop a project using its bootmux config",
        ));

    setup
        .cmd()
        .args(["debug", "l"])
        .assert()
        .success()
        .stdout(predicate::str::contains("new-session -d -s valid"));
}

#[test]
fn implode_removes_config_directories() {
    let setup = TestSetup::new();
    setup.write_project("any", VALID_PROJECT);

    setup
        .cmd()
        .arg("implode")
        .write_stdin("y\n")
        .assert()
        .success()
        .stdout(predicate::str::contains("Deleted all bootmux projects."));
    assert!(!setup.config_dir.path().exists());
}

#[test]
fn doctor_reports_environment_checks() {
    let setup = TestSetup::new();
    let assert = setup.cmd().arg("doctor").assert().success();
    let output = String::from_utf8(assert.get_output().stdout.clone()).unwrap();
    assert!(output.contains("Checking if tmux is installed ==> "));
    assert!(output.contains("Checking if $EDITOR is set ==> "));
    assert!(output.contains("Checking if $SHELL is set ==> "));
}

#[test]
fn projects_in_subdirectories_are_found_by_basename() {
    let setup = TestSetup::new();
    let sub = setup.config_dir.path().join("team");
    std::fs::create_dir_all(&sub).unwrap();
    std::fs::write(sub.join("nested.yml"), "name: nested\nwindows: []\n").unwrap();

    setup
        .cmd()
        .args(["debug", "nested"])
        .assert()
        .code(1)
        .stdout("Your project file should include some windows.\n");

    setup
        .cmd()
        .args(["list", "-n"])
        .assert()
        .success()
        .stdout("bootmux projects:\nteam/nested\n");

    setup
        .cmd()
        .args(["debug", "team/nested"])
        .assert()
        .code(1)
        .stdout("Your project file should include some windows.\n");
}

#[test]
fn backend_selection_supports_explicit_environment_and_global_default() {
    let setup = TestSetup::new();
    setup.write_project(
        "demo",
        "name: demo\nattach: false\nwindows:\n  - app: echo hi\n",
    );

    setup
        .cmd()
        .args(["--backend", "herdr", "debug", "demo"])
        .assert()
        .success()
        .stdout(predicate::str::contains("backend: herdr"))
        .stdout(predicate::str::contains("project: demo"));

    setup
        .cmd()
        .env("HERDR_ENV", "1")
        .args(["debug", "demo"])
        .assert()
        .success()
        .stdout(predicate::str::contains("backend: herdr"));

    setup
        .cmd()
        .env("HERDR_ACTIVE_WORKSPACE_ID", "w-test")
        .env("TMUX", "/tmp/tmux,1,1")
        .args(["debug", "demo"])
        .assert()
        .success()
        .stdout(predicate::str::contains("backend: herdr"));

    setup
        .cmd()
        .env("HERDR_ENV", "1")
        .args(["--backend", "tmux", "debug", "demo"])
        .assert()
        .success()
        .stdout(predicate::str::contains("new-session -d -s demo"))
        .stdout(predicate::str::contains("backend: herdr").not());

    setup
        .cmd()
        .args(["config", "set", "default-backend", "herdr"])
        .assert()
        .success()
        .stdout("default_backend = \"herdr\"\n");
    setup
        .cmd()
        .args(["debug", "demo"])
        .assert()
        .success()
        .stdout(predicate::str::contains("backend: herdr"));
}

#[test]
fn backend_global_option_works_with_project_shorthand() {
    let setup = TestSetup::new();
    setup.write_project("broken", "name: broken\nwindows: []\n");

    setup
        .cmd()
        .args(["--backend", "herdr", "broken"])
        .assert()
        .code(1)
        .stdout("Your project file should include some windows.\n");

    setup
        .cmd()
        .args(["broken", "--backend=herdr"])
        .assert()
        .code(1)
        .stdout("Your project file should include some windows.\n");
}

#[test]
fn config_and_binding_commands_are_stable() {
    let setup = TestSetup::new();
    let expected_path = setup.home_dir.path().join(".config/bootmux/config.toml");

    setup
        .cmd()
        .args(["config", "path"])
        .assert()
        .success()
        .stdout(format!("{}\n", expected_path.display()));
    setup
        .cmd()
        .args(["config", "get", "default-backend"])
        .assert()
        .success()
        .stdout("");

    setup
        .cmd()
        .args(["bindings", "tmux"])
        .assert()
        .success()
        .stdout("bind-key F new-window \"bootmux picker\"\n");
    setup
        .cmd()
        .args(["bindings", "tmux", "--key", "C-f"])
        .assert()
        .success()
        .stdout("bind-key C-f new-window \"bootmux picker\"\n");
    setup
        .cmd()
        .args(["bindings", "tmux", "--backend", "herdr"])
        .assert()
        .success()
        .stdout("bind-key F new-window \"bootmux picker\"\n");
    setup
        .cmd()
        .args(["bindings", "herdr"])
        .assert()
        .success()
        .stdout(predicate::str::contains("[[keys.command]]"))
        .stdout(predicate::str::contains("key = \"prefix+shift+f\""))
        .stdout(predicate::str::contains("width = \"80%\""));
    setup
        .cmd()
        .args(["bindings", "zellij"])
        .assert()
        .success()
        .stdout(predicate::str::contains("keybinds {"))
        .stdout(predicate::str::contains("shared_except \"locked\""))
        .stdout(predicate::str::contains("bind \"Ctrl y\""))
        .stdout(predicate::str::contains("Run \"bootmux\" \"picker\""));
}

#[test]
fn zellij_backend_is_selectable_explicitly_by_environment_and_by_default() {
    let setup = TestSetup::new();
    setup.write_project(
        "demo",
        "name: demo\nattach: false\nwindows:\n  - app: echo hi\n",
    );

    setup
        .cmd()
        .args(["--backend", "zellij", "debug", "demo"])
        .assert()
        .success()
        .stdout(predicate::str::contains("backend: zellij"))
        .stdout(predicate::str::contains("session: demo"))
        .stdout(predicate::str::contains("tab name=\"app\""));

    // zellij sets ZELLIJ to the literal "0" inside a session.
    setup
        .cmd()
        .env("ZELLIJ", "0")
        .args(["debug", "demo"])
        .assert()
        .success()
        .stdout(predicate::str::contains("backend: zellij"));

    setup
        .cmd()
        .args(["config", "set", "default-backend", "zellij"])
        .assert()
        .success()
        .stdout("default_backend = \"zellij\"\n");
    setup
        .cmd()
        .args(["debug", "demo"])
        .assert()
        .success()
        .stdout(predicate::str::contains("backend: zellij"));
}

#[test]
fn nested_multiplexer_environments_name_every_candidate() {
    let setup = TestSetup::new();
    setup.write_project(
        "demo",
        "name: demo\nattach: false\nwindows:\n  - app: echo hi\n",
    );

    setup
        .cmd()
        .env("TMUX", "/tmp/tmux,1,1")
        .env("ZELLIJ", "0")
        .args(["debug", "demo"])
        .assert()
        .failure()
        .stdout(predicate::str::contains("ambiguous"))
        .stdout(predicate::str::contains("tmux"))
        .stdout(predicate::str::contains("zellij"))
        .stdout(predicate::str::contains("--backend"));
}

#[cfg(unix)]
#[test]
fn zellij_doctor_checks_for_a_supported_version() {
    let setup = TestSetup::new();
    let assert = setup
        .cmd_with_supported_zellij()
        .args(["--backend", "zellij", "doctor"])
        .assert()
        .success();
    let output = String::from_utf8(assert.get_output().stdout.clone()).unwrap();
    assert!(
        output.contains("Checking if zellij >= 0.44.0 is installed ==> Yes"),
        "{output}"
    );
}

#[cfg(unix)]
#[test]
fn picker_cancel_is_success_and_selection_reuses_backend_resolution() {
    let setup = TestSetup::new();
    setup.write_project("broken", "name: broken\nwindows: []\n");

    setup
        .cmd_with_fake_fzf("#!/bin/sh\ncat >/dev/null\nexit 1\n")
        .arg("picker")
        .assert()
        .success()
        .stdout("");

    setup
        .cmd_with_fake_fzf("#!/bin/sh\ncat >/dev/null\nprintf 'broken\\n'\n")
        .env("HERDR_ENV", "1")
        .arg("picker")
        .assert()
        .code(1)
        .stdout("Your project file should include some windows.\n");
}

#[cfg(unix)]
#[test]
fn bare_invocation_without_local_project_opens_picker() {
    let setup = TestSetup::new();
    setup
        .cmd_with_fake_fzf("#!/bin/sh\ncat >/dev/null\nexit 130\n")
        .assert()
        .success()
        .stdout("");
}

#[test]
fn herdr_debug_validates_native_chain_without_contacting_a_server() {
    let setup = TestSetup::new();
    setup.write_project(
        "chain",
        r#"
name: chain
attach: false
windows:
  - app:
      panes:
        - editor:
            command: nvim
        - server:
            split: down
            ratio: 0.65
            commands: [npm run dev]
"#,
    );
    setup
        .cmd()
        .args(["--backend", "herdr", "debug", "chain"])
        .env("PATH", "/definitely/no/herdr")
        .assert()
        .success()
        .stdout(predicate::str::contains("split down ratio=0.6500"))
        .stdout(predicate::str::contains("pane[1] label=\"server\""));
}
