use assert_cmd::Command;
use predicates::prelude::*;
use tempfile::TempDir;

struct TestSetup {
    config_dir: TempDir,
    home_dir: TempDir,
    work_dir: TempDir,
}

impl TestSetup {
    fn new() -> Self {
        TestSetup {
            config_dir: TempDir::new().unwrap(),
            home_dir: TempDir::new().unwrap(),
            work_dir: TempDir::new().unwrap(),
        }
    }

    fn write_project(&self, name: &str, content: &str) {
        std::fs::write(self.config_dir.path().join(format!("{name}.yml")), content).unwrap();
    }

    fn cmd(&self) -> Command {
        let mut cmd = Command::cargo_bin("bootmux").unwrap();
        cmd.env_clear()
            .env("PATH", std::env::var("PATH").unwrap())
            .env("HOME", self.home_dir.path())
            .env("TMUXINATOR_CONFIG", self.config_dir.path())
            .env("SHELL", "/bin/bash")
            .env("EDITOR", "true")
            .current_dir(self.work_dir.path());
        cmd
    }
}

const VALID_PROJECT: &str = "name: valid\nattach: false\nwindows:\n  - editor: vim\n";

#[test]
fn version_prints_bootmux_version() {
    let setup = TestSetup::new();
    setup
        .cmd()
        .arg("version")
        .assert()
        .success()
        .stdout(format!("bootmux {}\n", env!("CARGO_PKG_VERSION")));

    setup
        .cmd()
        .arg("-v")
        .assert()
        .success()
        .stdout(predicate::str::starts_with("bootmux "));
}

#[test]
fn commands_lists_all_command_names() {
    let setup = TestSetup::new();
    let assert = setup.cmd().arg("commands").assert().success();
    let output = String::from_utf8(assert.get_output().stdout.clone()).unwrap();
    for name in ["start", "stop", "stop_all", "debug", "implode", "version"] {
        assert!(output.lines().any(|line| line == name), "missing {name}");
    }

    setup
        .cmd()
        .args(["commands", "zsh"])
        .assert()
        .success()
        .stdout(predicate::str::contains(
            "debug:Output the shell commands that are generated by bootmux",
        ));
}

#[test]
fn completions_lists_projects_for_completable_commands() {
    let setup = TestSetup::new();
    setup.write_project("alpha", VALID_PROJECT);
    setup.write_project("beta", VALID_PROJECT);

    setup
        .cmd()
        .args(["completions", "start"])
        .assert()
        .success()
        .stdout("alpha\nbeta\n");

    setup
        .cmd()
        .args(["completions", "doctor"])
        .assert()
        .success()
        .stdout("");
}

#[test]
fn list_shows_projects() {
    let setup = TestSetup::new();
    setup.write_project("alpha", VALID_PROJECT);
    setup.write_project("beta", VALID_PROJECT);

    setup
        .cmd()
        .args(["list", "--newline"])
        .assert()
        .success()
        .stdout("bootmux projects:\nalpha\nbeta\n");
}

#[test]
fn debug_renders_project_script() {
    let setup = TestSetup::new();
    setup.write_project("demo", "name: demo\nwindows:\n  - editor: vim\n");

    setup
        .cmd()
        .args(["debug", "demo"])
        .assert()
        .success()
        .stdout(predicate::str::contains("new-session -d -s demo -n editor"))
        .stdout(predicate::str::contains("vim C-m"));
}

#[test]
fn debug_accepts_project_config_path_and_settings() {
    let setup = TestSetup::new();
    let config = setup.work_dir.path().join("templated.yml");
    std::fs::write(
        &config,
        "name: {{ settings.session | default('fallback') }}\nwindows:\n  - a: echo {{ args[0] }}\n",
    )
    .unwrap();

    setup
        .cmd()
        .args([
            "debug",
            "-p",
            config.to_str().unwrap(),
            "session=custom",
            "hello",
        ])
        .assert()
        .success()
        .stdout(predicate::str::contains("new-session -d -s custom"))
        .stdout(predicate::str::contains("echo\\ hello C-m"));
}

#[test]
fn project_name_shorthand_routes_to_start() {
    let setup = TestSetup::new();
    setup.write_project("broken", "name: broken\nwindows: []\n");

    setup
        .cmd()
        .arg("broken")
        .assert()
        .code(1)
        .stdout("Your project file should include some windows.\n");
}

#[test]
fn bare_invocation_uses_local_project_file() {
    let setup = TestSetup::new();
    std::fs::write(
        setup.work_dir.path().join(".tmuxinator.yml"),
        "name: local-broken\nwindows: []\n",
    )
    .unwrap();

    setup
        .cmd()
        .assert()
        .code(1)
        .stdout("Your project file should include some windows.\n");
}

#[test]
fn missing_projects_report_ruby_compatible_errors() {
    let setup = TestSetup::new();

    setup
        .cmd()
        .args(["start", "nosuch"])
        .assert()
        .code(1)
        .stdout("Project nosuch doesn't exist.\n");

    setup
        .cmd()
        .args(["stop"])
        .assert()
        .code(1)
        .stdout("Project file at ./.tmuxinator.yml doesn't exist.\n");

    setup
        .cmd()
        .args(["debug", "-p", "missing.yml"])
        .assert()
        .code(1)
        .stdout("Project config (missing.yml) doesn't exist.\n");
}

#[test]
fn erb_configs_are_rejected_with_migration_hint() {
    let setup = TestSetup::new();
    setup.write_project(
        "legacy",
        "name: legacy\nwindows:\n  - a: echo <%= @args[0] %>\n",
    );

    setup
        .cmd()
        .args(["debug", "legacy"])
        .assert()
        .code(1)
        .stdout(predicate::str::contains("Failed to parse config file:"))
        .stdout(predicate::str::contains("MiniJinja"));
}

#[test]
fn new_generates_project_from_sample_and_opens_editor() {
    let setup = TestSetup::new();

    setup.cmd().args(["new", "fresh"]).assert().success();

    let created = setup.config_dir.path().join("fresh.yml");
    let content = std::fs::read_to_string(&created).unwrap();
    assert!(content.contains("name: fresh"));
    assert!(content.contains(created.to_str().unwrap()));
}

#[test]
fn copy_duplicates_project_files() {
    let setup = TestSetup::new();
    setup.write_project("origin", VALID_PROJECT);

    setup
        .cmd()
        .args(["copy", "origin", "clone"])
        .assert()
        .success();
    assert!(setup.config_dir.path().join("clone.yml").exists());

    setup
        .cmd()
        .args(["copy", "nosuch", "clone2"])
        .assert()
        .code(1)
        .stdout("Project nosuch doesn't exist!\n");
}

#[test]
fn delete_removes_project_after_confirmation() {
    let setup = TestSetup::new();
    setup.write_project("doomed", VALID_PROJECT);

    setup
        .cmd()
        .args(["delete", "doomed"])
        .write_stdin("y\n")
        .assert()
        .success()
        .stdout(predicate::str::contains("Deleted doomed"));
    assert!(!setup.config_dir.path().join("doomed.yml").exists());

    setup
        .cmd()
        .args(["delete", "ghost"])
        .assert()
        .success()
        .stdout(predicate::str::contains("ghost does not exist!"));
}

#[test]
fn implode_removes_config_directories() {
    let setup = TestSetup::new();
    setup.write_project("any", VALID_PROJECT);

    setup
        .cmd()
        .arg("implode")
        .write_stdin("y\n")
        .assert()
        .success()
        .stdout(predicate::str::contains("Deleted all bootmux projects."));
    assert!(!setup.config_dir.path().exists());
}

#[test]
fn doctor_reports_environment_checks() {
    let setup = TestSetup::new();
    let assert = setup.cmd().arg("doctor").assert().success();
    let output = String::from_utf8(assert.get_output().stdout.clone()).unwrap();
    assert!(output.contains("Checking if tmux is installed ==> "));
    assert!(output.contains("Checking if $EDITOR is set ==> "));
    assert!(output.contains("Checking if $SHELL is set ==> "));
}

#[test]
fn projects_in_subdirectories_are_found_by_basename() {
    let setup = TestSetup::new();
    let sub = setup.config_dir.path().join("team");
    std::fs::create_dir_all(&sub).unwrap();
    std::fs::write(sub.join("nested.yml"), "name: nested\nwindows: []\n").unwrap();

    setup
        .cmd()
        .args(["debug", "nested"])
        .assert()
        .code(1)
        .stdout("Your project file should include some windows.\n");

    setup
        .cmd()
        .args(["list", "-n"])
        .assert()
        .success()
        .stdout("bootmux projects:\nteam/nested\n");
}
