use anyhow::Result;

use crate::config;
use crate::env::Env;
use crate::settings::Backend;
use crate::tmux::TmuxContext;
use crate::util::yes_no;

// Names and descriptions mirror tmuxinator's COMMANDS table (same order);
// the plain list feeds the static shell completion scripts.
const COMMAND_DESCRIPTIONS: [(&str, &str); 20] = [
    (
        "bindings",
        "Print a tmux or Herdr picker keybinding snippet",
    ),
    ("commands", "Lists commands available in bootmux"),
    ("completions", "Used for shell completion"),
    ("config", "Read or update bootmux global settings"),
    (
        "copy",
        "Copy an existing project to a new project and open it in your editor",
    ),
    (
        "debug",
        "Output the shell commands that are generated by bootmux",
    ),
    ("delete", "Deletes given project"),
    ("doctor", "Look for problems in your configuration"),
    ("edit", "Edit an existing project file in your editor"),
    ("help", "Shows help for a specific command"),
    ("implode", "Deletes all bootmux projects"),
    ("local", "Start a project using ./.tmuxinator.y[a]ml"),
    ("list", "Lists all bootmux projects"),
    (
        "new",
        "Create a new project file and open it in your editor",
    ),
    ("open", "Create or open a project file in your editor"),
    ("picker", "Select and start a project with fzf"),
    (
        "start",
        "Start a project by name or from a config path (via the -p flag)",
    ),
    ("stop", "Stop a project using its bootmux config"),
    (
        "stop_all",
        "Stop all managed projects for the selected backend",
    ),
    ("version", "Display installed bootmux version"),
];

pub fn commands(shell: Option<&str>) -> Result<()> {
    let output = if shell == Some("zsh") {
        COMMAND_DESCRIPTIONS
            .iter()
            .map(|(name, description)| format!("{name}:{description}"))
            .collect::<Vec<_>>()
            .join("\n")
    } else {
        COMMAND_DESCRIPTIONS
            .iter()
            .map(|(name, _)| name.to_string())
            .collect::<Vec<_>>()
            .join("\n")
    };
    println!("{output}");
    Ok(())
}

pub fn completions(env: &Env, arg: &str) -> Result<()> {
    if ["start", "stop", "edit", "open", "copy", "delete"].contains(&arg) {
        let configs = config::configs(env, None);
        println!("{}", configs.join("\n"));
    }
    Ok(())
}

pub fn list(env: &Env, ctx: &dyn TmuxContext, newline: bool, active: bool) -> Result<()> {
    list_with_backend(env, ctx, None, newline, active)
}

pub fn list_with_backend(
    env: &Env,
    ctx: &dyn TmuxContext,
    backend: Option<Backend>,
    newline: bool,
    active: bool,
) -> Result<()> {
    println!("bootmux projects:");
    let sessions = if active {
        match backend.unwrap_or(Backend::Tmux) {
            Backend::Tmux => ctx.active_sessions(),
            Backend::Herdr => crate::herdr_backend::active_project_names(env)?,
            Backend::Zellij => crate::zellij_backend::active_project_names(env)?,
        }
    } else {
        Vec::new()
    };
    let filter = if active {
        Some((true, sessions.as_slice()))
    } else {
        None
    };
    let configs = config::configs(env, filter);

    if newline {
        println!("{}", configs.join("\n"));
    } else {
        print_in_columns(&configs);
    }
    Ok(())
}

fn print_in_columns(items: &[String]) {
    if items.is_empty() {
        println!();
        return;
    }
    let terminal_width = terminal_size::terminal_size()
        .map(|(width, _)| width.0 as usize)
        .unwrap_or(80);
    let column_width = items.iter().map(String::len).max().unwrap_or(0) + 2;
    let per_line = (terminal_width / column_width).max(1);

    for chunk in items.chunks(per_line) {
        let row = chunk
            .iter()
            .map(|item| format!("{item:column_width$}"))
            .collect::<String>();
        println!("{}", row.trim_end());
    }
}

pub fn version() -> Result<()> {
    println!("bootmux {}", env!("CARGO_PKG_VERSION"));
    Ok(())
}

pub fn doctor(env: &Env) -> Result<()> {
    doctor_with_backend(env, Backend::Tmux)
}

pub fn doctor_with_backend(env: &Env, backend: Backend) -> Result<()> {
    match backend {
        Backend::Tmux => {
            print!("Checking if tmux is installed ==> ");
            yes_no(command_installed("tmux"));
        }
        Backend::Herdr => {
            print!(
                "Checking if Herdr >= {} (protocol {}) is installed ==> ",
                crate::herdr::MINIMUM_HERDR_VERSION,
                crate::herdr::describe_protocols(crate::herdr::SUPPORTED_PROTOCOLS)
            );
            yes_no(crate::herdr_backend::doctor_compatible(env));
        }
        Backend::Zellij => {
            print!(
                "Checking if zellij >= {} is installed ==> ",
                crate::zellij::MINIMUM_VERSION
            );
            yes_no(crate::zellij_backend::doctor_compatible(env));
        }
    }

    print!("Checking if optional fzf picker is installed ==> ");
    yes_no(command_installed("fzf"));

    doctor_environment(env)
}

pub fn doctor_environment(env: &Env) -> Result<()> {
    print!("Checking if $EDITOR is set ==> ");
    yes_no(!env.editor.as_deref().unwrap_or_default().is_empty());

    print!("Checking if $SHELL is set ==> ");
    yes_no(!env.shell.as_deref().unwrap_or_default().is_empty());
    Ok(())
}

fn command_installed(program: &str) -> bool {
    std::process::Command::new("sh")
        .arg("-c")
        .arg(format!(
            "command -v {} > /dev/null",
            crate::shellwords::escape(program)
        ))
        .status()
        .map(|status| status.success())
        .unwrap_or(false)
}
