use anyhow::Result;

use crate::config;
use crate::env::Env;
use crate::tmux::TmuxContext;
use crate::util::yes_no;

// Names and descriptions mirror tmuxinator's COMMANDS table (same order);
// the plain list feeds the static shell completion scripts.
const COMMAND_DESCRIPTIONS: [(&str, &str); 17] = [
    ("commands", "Lists commands available in bootmux"),
    ("completions", "Used for shell completion"),
    (
        "copy",
        "Copy an existing project to a new project and open it in your editor",
    ),
    ("debug", "Output the shell commands that are generated by bootmux"),
    ("delete", "Deletes given project"),
    ("doctor", "Look for problems in your configuration"),
    ("edit", "Edit an existing project file in your editor"),
    ("help", "Shows help for a specific command"),
    ("implode", "Deletes all bootmux projects"),
    ("local", "Start a tmux session using ./.tmuxinator.y[a]ml"),
    ("list", "Lists all bootmux projects"),
    ("new", "Create a new project file and open it in your editor"),
    ("open", "Create or open a project file in your editor"),
    (
        "start",
        "Start a tmux session using a project's name (with an optional [ALIAS] for project reuse) or a path to a project config file (via the -p flag)",
    ),
    ("stop", "Stop a tmux session using a project's bootmux config"),
    ("stop_all", "Stop all tmux sessions which are using bootmux projects"),
    ("version", "Display installed bootmux version"),
];

pub fn commands(shell: Option<&str>) -> Result<()> {
    let output = if shell == Some("zsh") {
        COMMAND_DESCRIPTIONS
            .iter()
            .map(|(name, description)| format!("{name}:{description}"))
            .collect::<Vec<_>>()
            .join("\n")
    } else {
        COMMAND_DESCRIPTIONS
            .iter()
            .map(|(name, _)| name.to_string())
            .collect::<Vec<_>>()
            .join("\n")
    };
    println!("{output}");
    Ok(())
}

pub fn completions(env: &Env, arg: &str) -> Result<()> {
    if ["start", "stop", "edit", "open", "copy", "delete"].contains(&arg) {
        let configs = config::configs(env, None);
        println!("{}", configs.join("\n"));
    }
    Ok(())
}

pub fn list(env: &Env, ctx: &dyn TmuxContext, newline: bool, active: bool) -> Result<()> {
    println!("bootmux projects:");
    let sessions = ctx.active_sessions();
    let filter = if active {
        Some((true, sessions.as_slice()))
    } else {
        None
    };
    let configs = config::configs(env, filter);

    if newline {
        println!("{}", configs.join("\n"));
    } else {
        print_in_columns(&configs);
    }
    Ok(())
}

fn print_in_columns(items: &[String]) {
    if items.is_empty() {
        println!();
        return;
    }
    let terminal_width = terminal_size::terminal_size()
        .map(|(width, _)| width.0 as usize)
        .unwrap_or(80);
    let column_width = items.iter().map(String::len).max().unwrap_or(0) + 2;
    let per_line = (terminal_width / column_width).max(1);

    for chunk in items.chunks(per_line) {
        let row = chunk
            .iter()
            .map(|item| format!("{item:column_width$}"))
            .collect::<String>();
        println!("{}", row.trim_end());
    }
}

pub fn version() -> Result<()> {
    println!("bootmux {}", env!("CARGO_PKG_VERSION"));
    Ok(())
}

pub fn doctor(env: &Env) -> Result<()> {
    print!("Checking if tmux is installed ==> ");
    yes_no(tmux_installed());

    print!("Checking if $EDITOR is set ==> ");
    yes_no(!env.editor.as_deref().unwrap_or_default().is_empty());

    print!("Checking if $SHELL is set ==> ");
    yes_no(!env.shell.as_deref().unwrap_or_default().is_empty());
    Ok(())
}

fn tmux_installed() -> bool {
    std::process::Command::new("sh")
        .arg("-c")
        .arg("type tmux > /dev/null")
        .status()
        .map(|status| status.success())
        .unwrap_or(false)
}
