use clap::{Parser, Subcommand};

use crate::commands;
use crate::config;
use crate::env::Env;
use crate::settings::Backend;
use crate::tmux::RealTmux;
use crate::util::exit_with_message;

// Command names and aliases must take precedence over project shorthand.
// Keep this in sync with Clap's top-level subcommands.
const RESERVED_COMMANDS: &[&str] = &[
    "bindings",
    "commands",
    "completions",
    "config",
    "copy",
    "debug",
    "delete",
    "doctor",
    "edit",
    "help",
    "implode",
    "local",
    "list",
    "new",
    "open",
    "picker",
    "start",
    "stop",
    "stop_all",
    "stop-all",
    "version",
    "-v",
    "-h",
    "--help",
    ".",
    "c",
    "cp",
    "d",
    "e",
    "i",
    "l",
    "ls",
    "n",
    "o",
    "rm",
    "s",
    "st",
];

#[derive(Parser)]
#[command(
    name = "bootmux",
    about = "Manage tmux sessions and Herdr workspaces from tmuxinator-compatible YAML",
    override_usage = "bootmux [OPTIONS] [COMMAND]",
    disable_version_flag = true
)]
pub struct Cli {
    /// Select a backend explicitly. Otherwise bootmux uses the active
    /// multiplexer, then the configured global default.
    #[arg(long, global = true, value_parser = ["tmux", "herdr"])]
    pub backend: Option<String>,
    #[command(subcommand)]
    pub command: Command,
}

#[derive(Subcommand)]
pub enum Command {
    /// Start a project using its name or a config path
    #[command(visible_alias = "s")]
    Start {
        project: Option<String>,
        #[arg(num_args = 0..)]
        args: Vec<String>,
        /// Attach/focus after creation
        #[arg(short = 'a', long)]
        attach: bool,
        /// Do not attach/focus after creation
        #[arg(long, conflicts_with = "attach")]
        no_attach: bool,
        /// Give the session a different name
        #[arg(short = 'n', long)]
        name: Option<String>,
        /// Path to project config file
        #[arg(short = 'p', long = "project-config")]
        project_config: Option<String>,
        /// Don't show a warning for unsupported tmux versions
        #[arg(long = "suppress-tmux-version-warning")]
        suppress_tmux_version_warning: bool,
        /// Appends the project windows and panes in the current session
        #[arg(long)]
        append: bool,
        /// Skip pre_window commands
        #[arg(long = "no-pre-window")]
        no_pre_window: bool,
    },
    /// Stop a project using its bootmux config
    #[command(visible_alias = "st")]
    Stop {
        project: Option<String>,
        /// Template settings and positional template arguments
        #[arg(num_args = 0..)]
        args: Vec<String>,
        /// Path to project config file
        #[arg(short = 'p', long = "project-config")]
        project_config: Option<String>,
        /// Don't show a warning for unsupported tmux versions
        #[arg(long = "suppress-tmux-version-warning")]
        suppress_tmux_version_warning: bool,
    },
    /// Stop all managed projects for the selected backend
    #[command(name = "stop-all", alias = "stop_all")]
    StopAll {
        /// Skip confirmation
        #[arg(short = 'y', long)]
        noconfirm: bool,
    },
    /// Start a project using ./.tmuxinator.y[a]ml
    #[command(visible_alias = ".")]
    Local {
        /// Don't show a warning for unsupported tmux versions
        #[arg(long = "suppress-tmux-version-warning")]
        suppress_tmux_version_warning: bool,
    },
    /// Output the backend plan generated by bootmux
    Debug {
        project: Option<String>,
        #[arg(num_args = 0..)]
        args: Vec<String>,
        /// Attach/focus after creation
        #[arg(short = 'a', long)]
        attach: bool,
        /// Do not attach/focus after creation
        #[arg(long, conflicts_with = "attach")]
        no_attach: bool,
        /// Give the session a different name
        #[arg(short = 'n', long)]
        name: Option<String>,
        /// Path to project config file
        #[arg(short = 'p', long = "project-config")]
        project_config: Option<String>,
        /// Appends the project windows and panes in the current session
        #[arg(long)]
        append: bool,
        /// Skip pre_window commands
        #[arg(long = "no-pre-window")]
        no_pre_window: bool,
    },
    /// Create a new project file and open it in your editor
    #[command(visible_alias = "n")]
    New {
        name: String,
        /// Create the project from an existing tmux session
        session: Option<String>,
        /// Use local project file at ./.tmuxinator.yml
        #[arg(short = 'l', long)]
        local: bool,
    },
    /// Create or open a project file in your editor
    #[command(visible_alias = "o")]
    Open {
        name: String,
        /// Use local project file at ./.tmuxinator.yml
        #[arg(short = 'l', long)]
        local: bool,
    },
    /// Edit an existing project file in your editor
    #[command(visible_alias = "e")]
    Edit {
        name: Option<String>,
        /// Use local project file at ./.tmuxinator.yml
        #[arg(short = 'l', long)]
        local: bool,
    },
    /// Copy an existing project to a new project and open it in your editor
    #[command(visible_alias = "c", visible_alias = "cp")]
    Copy { existing: String, new: String },
    /// Deletes given project
    #[command(visible_alias = "d", visible_alias = "rm")]
    Delete {
        #[arg(required = true, num_args = 1..)]
        projects: Vec<String>,
    },
    /// Deletes all bootmux projects
    #[command(visible_alias = "i")]
    Implode,
    /// Lists all bootmux projects
    #[command(visible_alias = "l", visible_alias = "ls")]
    List {
        /// Force output to be one entry per line
        #[arg(short = 'n', long)]
        newline: bool,
        /// Filter output by active project sessions
        #[arg(short = 'a', long)]
        active: bool,
    },
    /// Display installed bootmux version
    Version,
    /// Look for problems in your configuration
    Doctor,
    /// Select a project interactively with fzf
    Picker,
    /// Print a tmux or Herdr picker binding snippet
    Bindings {
        #[arg(id = "bindings_backend", value_parser = ["tmux", "herdr"])]
        backend: String,
        /// Override the default key
        #[arg(long)]
        key: Option<String>,
    },
    /// Read or update bootmux's global settings
    Config {
        #[command(subcommand)]
        action: ConfigAction,
    },
    /// Used for shell completion
    Completions { arg: String },
    /// Lists commands available in bootmux
    Commands { shell: Option<String> },
}

#[derive(Subcommand)]
pub enum ConfigAction {
    /// Print a setting
    Get {
        #[arg(value_parser = ["default-backend"])]
        key: String,
    },
    /// Change a setting
    Set {
        #[arg(value_parser = ["default-backend"])]
        key: String,
        #[arg(value_parser = ["tmux", "herdr"])]
        value: String,
    },
    /// Print the global settings file path
    Path,
}

pub fn bootstrap(mut args: Vec<String>, env: Env) {
    if args.first().map(String::as_str) == Some("-v") {
        args[0] = "version".to_string();
    }

    if let Some(index) = command_token_index(&args) {
        let first = args[index].clone();
        if !RESERVED_COMMANDS.contains(&first.as_str()) && config::project_exists(&env, &first) {
            args.insert(index, "start".to_string());
        }
    }
    if command_token_index(&args).is_none() && args.last().map(String::as_str) != Some("--backend")
    {
        args.push(
            if config::local_project(&env).is_some() {
                "local"
            } else {
                "picker"
            }
            .to_string(),
        );
    }

    let mut argv = vec!["bootmux".to_string()];
    argv.extend(args);
    let cli = Cli::parse_from(argv);

    let backend = cli
        .backend
        .as_deref()
        .map(str::parse::<Backend>)
        .transpose()
        .unwrap_or_else(|error| exit_with_message(&error.to_string()));
    let ctx = RealTmux;
    if let Err(error) = commands::dispatch_with_backend(cli.command, backend, &env, &ctx) {
        exit_with_message(&format!("{error:#}"));
    }
}

fn command_token_index(args: &[String]) -> Option<usize> {
    let mut index = 0;
    while index < args.len() {
        match args[index].as_str() {
            "--backend" => index += 2,
            value if value.starts_with("--backend=") => index += 1,
            value if value.starts_with('-') => return Some(index),
            _ => return Some(index),
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use clap::CommandFactory;

    use super::{command_token_index, Cli, RESERVED_COMMANDS};

    #[test]
    fn finds_command_after_global_backend() {
        assert_eq!(
            command_token_index(&["--backend".into(), "herdr".into(), "demo".into()]),
            Some(2)
        );
        assert_eq!(
            command_token_index(&["--backend=tmux".into(), "start".into()]),
            Some(1)
        );
        assert_eq!(command_token_index(&["--backend".into()]), None);
    }

    #[test]
    fn reserves_every_command_name_and_alias_from_project_shorthand() {
        for command in Cli::command().get_subcommands() {
            assert!(
                RESERVED_COMMANDS.contains(&command.get_name()),
                "command name {} is not reserved",
                command.get_name()
            );
            for alias in command.get_all_aliases() {
                assert!(
                    RESERVED_COMMANDS.contains(&alias),
                    "command alias {alias} is not reserved"
                );
            }
        }
    }
}
