use clap::{Parser, Subcommand};

use crate::commands;
use crate::config;
use crate::env::Env;
use crate::tmux::RealTmux;
use crate::util::exit_with_message;

// Port of Ruby RESERVED_COMMANDS: full command names only (not short
// aliases), used by bootstrap to decide whether the first argument is a
// project name. "stop-all" is included alongside "stop_all" because clap
// exposes the dashed form.
const RESERVED_COMMANDS: [&str; 21] = [
    "commands",
    "completions",
    "copy",
    "debug",
    "delete",
    "doctor",
    "edit",
    "help",
    "implode",
    "local",
    "list",
    "new",
    "open",
    "start",
    "stop",
    "stop_all",
    "stop-all",
    "version",
    "-v",
    "-h",
    "--help",
];

#[derive(Parser)]
#[command(
    name = "bootmux",
    about = "Create and manage tmux sessions easily (a Rust port of tmuxinator)",
    disable_version_flag = true
)]
pub struct Cli {
    #[command(subcommand)]
    pub command: Command,
}

#[derive(Subcommand)]
pub enum Command {
    /// Start a tmux session using a project's name (with optional extra
    /// args) or a path to a project config file (via the -p flag)
    #[command(visible_alias = "s")]
    Start {
        project: Option<String>,
        #[arg(num_args = 0..)]
        args: Vec<String>,
        /// Attach to tmux session after creation
        #[arg(short = 'a', long)]
        attach: bool,
        /// Do not attach to the tmux session
        #[arg(long, conflicts_with = "attach")]
        no_attach: bool,
        /// Give the session a different name
        #[arg(short = 'n', long)]
        name: Option<String>,
        /// Path to project config file
        #[arg(short = 'p', long = "project-config")]
        project_config: Option<String>,
        /// Don't show a warning for unsupported tmux versions
        #[arg(long = "suppress-tmux-version-warning")]
        suppress_tmux_version_warning: bool,
        /// Appends the project windows and panes in the current session
        #[arg(long)]
        append: bool,
        /// Skip pre_window commands
        #[arg(long = "no-pre-window")]
        no_pre_window: bool,
    },
    /// Stop a tmux session using a project's bootmux config
    #[command(visible_alias = "st")]
    Stop {
        project: Option<String>,
        /// Path to project config file
        #[arg(short = 'p', long = "project-config")]
        project_config: Option<String>,
        /// Don't show a warning for unsupported tmux versions
        #[arg(long = "suppress-tmux-version-warning")]
        suppress_tmux_version_warning: bool,
    },
    /// Stop all tmux sessions which are using bootmux projects
    #[command(name = "stop-all", alias = "stop_all")]
    StopAll {
        /// Skip confirmation
        #[arg(short = 'y', long)]
        noconfirm: bool,
    },
    /// Start a tmux session using ./.tmuxinator.y[a]ml
    #[command(visible_alias = ".")]
    Local {
        /// Don't show a warning for unsupported tmux versions
        #[arg(long = "suppress-tmux-version-warning")]
        suppress_tmux_version_warning: bool,
    },
    /// Output the shell commands that are generated by bootmux
    Debug {
        project: Option<String>,
        #[arg(num_args = 0..)]
        args: Vec<String>,
        /// Attach to tmux session after creation
        #[arg(short = 'a', long)]
        attach: bool,
        /// Do not attach to the tmux session
        #[arg(long, conflicts_with = "attach")]
        no_attach: bool,
        /// Give the session a different name
        #[arg(short = 'n', long)]
        name: Option<String>,
        /// Path to project config file
        #[arg(short = 'p', long = "project-config")]
        project_config: Option<String>,
        /// Appends the project windows and panes in the current session
        #[arg(long)]
        append: bool,
        /// Skip pre_window commands
        #[arg(long = "no-pre-window")]
        no_pre_window: bool,
    },
    /// Create a new project file and open it in your editor
    #[command(visible_alias = "n")]
    New {
        name: String,
        /// Create the project from an existing tmux session
        session: Option<String>,
        /// Use local project file at ./.tmuxinator.yml
        #[arg(short = 'l', long)]
        local: bool,
    },
    /// Create or open a project file in your editor
    #[command(visible_alias = "o")]
    Open {
        name: String,
        /// Use local project file at ./.tmuxinator.yml
        #[arg(short = 'l', long)]
        local: bool,
    },
    /// Edit an existing project file in your editor
    #[command(visible_alias = "e")]
    Edit {
        name: Option<String>,
        /// Use local project file at ./.tmuxinator.yml
        #[arg(short = 'l', long)]
        local: bool,
    },
    /// Copy an existing project to a new project and open it in your editor
    #[command(visible_alias = "c", visible_alias = "cp")]
    Copy { existing: String, new: String },
    /// Deletes given project
    #[command(visible_alias = "d", visible_alias = "rm")]
    Delete {
        #[arg(required = true, num_args = 1..)]
        projects: Vec<String>,
    },
    /// Deletes all bootmux projects
    #[command(visible_alias = "i")]
    Implode,
    /// Lists all bootmux projects
    #[command(visible_alias = "l", visible_alias = "ls")]
    List {
        /// Force output to be one entry per line
        #[arg(short = 'n', long)]
        newline: bool,
        /// Filter output by active project sessions
        #[arg(short = 'a', long)]
        active: bool,
    },
    /// Display installed bootmux version
    Version,
    /// Look for problems in your configuration
    Doctor,
    /// Used for shell completion
    Completions { arg: String },
    /// Lists commands available in bootmux
    Commands { shell: Option<String> },
}

pub fn bootstrap(mut args: Vec<String>, env: Env) {
    if args.first().map(String::as_str) == Some("-v") {
        args[0] = "version".to_string();
    }

    let ctx = RealTmux;

    if args.is_empty() && config::local_project(&env).is_some() {
        if let Err(error) = commands::run::local(&env, &ctx, false) {
            exit_with_message(&error.to_string());
        }
        return;
    }

    if let Some(first) = args.first().cloned() {
        if !RESERVED_COMMANDS.contains(&first.as_str()) && config::project_exists(&env, &first) {
            args.insert(0, "start".to_string());
        }
    }

    let mut argv = vec!["bootmux".to_string()];
    argv.extend(args);
    let cli = Cli::parse_from(argv);

    if let Err(error) = commands::dispatch(cli.command, &env, &ctx) {
        exit_with_message(&error.to_string());
    }
}
